#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
#  default:
#      - step:
#          deployment: test
#          caches:
#            - node
#          script:
#            - echo "start build test"
#            - npm install
#            - npm run build
  branches:
    dev:
      - step:
          name: build development
          deployment: test
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                MODE: 'script'
                COMMAND: $DEV_BUILD
    main:
      - step:
          name: build production
          deployment: production
          caches:
              - node
          script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: $USER
                SERVER: $SERVER
                MODE: 'script'
                COMMAND: $PROD_BUILD
  pull-requests:
#    '**': #모든 브렌치에서 실행되는 예제
#      - step:
#          deployment: test
#          script:
#            - pipe: atlassian/ssh-run:0.4.1
#              variables:
#                SSH_USER: $USER
#                SERVER: $SERVER
#                MODE: 'script'
#                COMMAND: $DEV_BUILD
    release/*: #release 브렌치에서 실행되는 예제
      - step:
          deployment: staging
          caches:
            - node
          script:
            - echo "start build test"
            - npm install
            - npm run build:prod
    dev: #release 브렌치에서 실행되는 예제
      - step:
          deployment: staging
          caches:
            - node
          script:
            - echo "start build test"
            - npm install
            - npm run build
    main: #release 브렌치에서 실행되는 예제
      - step:
          deployment: staging
          caches:
            - node
          script:
            - echo "start build test"
            - npm install
            - npm run build:prod

  