#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
      - step:
          deployment: test
          script:
            - echo "start build test"
            - npm run dev 
  branches:
    test:
      - step:
          name: build test
          deployment: test
          caches:
              - node
          script: 
            - echo "start build test"
            - npm install
            - npm run build
            - npm run dev 
    master:
      - step:
          name: build pubilsh
          deployment: production
          caches:
              - node
          script: 
            - echo "start build publish"
            - npm install
            - npm run build
            - npm run dev
  pull-requests:
    '**': #모든 브렌치에서 실행되는 예제
      - step:
          script:
            - echo "start all pr merge & deploy"
            - npm install
            - npm run dev 
    release/*: #release 브렌치에서 실행되는 예제
      - step:
          script:
            - echo "start all pr merge & deploy"
            - npm install
            - npm run dev 

  