#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

#image: node:16
image: atlassian/default-image:4

pipelines:
  branches:
    master:
      - step:
          name: building chai-monorepo app & S3 deploy
          caches:
            - node
          script:
            - apt-get update
            - apt-get install -y zip
            - npm install
            - npm run build
            - zip -r build-chai-monorepo.zip appspec.yml packages/chai-contents-creator-v2/build packages/chai-contents-view-v2/build
            - pipe: atlassian/aws-code-deploy:1.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                ZIP_FILE: "build-chai-monorepo.zip"
                COMMAND: "upload"
                VERSION_LABEL: "build-chai-monorepo-1.0.0"
          artifacts:
            - build-chai-monorepo.zip
      - step:
          name: deploy chai-monorepo app
          script:
            - pipe: atlassian/aws-code-deploy:1.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: "deploy"
                IGNORE_APPLICATION_STOP_FAILURES: "true"
                FILE_EXISTS_BEHAVIOR: "OVERWRITE"
                WAIT: "true"
                VERSION_LABEL: "build-chai-monorepo-1.0.0"
    # dev:
    #   - step:
    #       name: building chai-monorepo app & S3 deploy
    #       caches:
    #         - node
    #       script:
    #         - apt-get update
    #         - apt-get install -y zip
    #         - npm install
    #         - npm run build
  #            - zip -r build-chai-monorepo-dev.zip appspec.yml packages/chai-contents-creator/build packages/chai-contents-view/build
  #            - pipe: atlassian/aws-code-deploy:1.1.1
  #              variables:
  #                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  #                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  #                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  #                APPLICATION_NAME: $APPLICATION_NAME
  #                S3_BUCKET: $S3_BUCKET
  #                ZIP_FILE: 'build-chai-monorepo-dev.zip'
  #                COMMAND: 'upload'
  #                VERSION_LABEL: 'build-chai-monorepo-dev-1.0.0'
  #          artifacts:
  #            - build-chai-monorepo-dev.zip
  #      - step:
  #          name: deploy chai-monorepo app
  #          script:
  #            - pipe: atlassian/aws-code-deploy:1.1.1
  #              variables:
  #                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  #                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  #                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  #                APPLICATION_NAME: $APPLICATION_NAME
  #                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
  #                S3_BUCKET: $S3_BUCKET
  #                COMMAND: 'deploy'
  #                IGNORE_APPLICATION_STOP_FAILURES: 'true'
  #                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
  #                WAIT: 'true'
  #                VERSION_LABEL: 'build-chai-monorepo-dev-1.0.0'
  pull-requests:
    master:
      - step:
          name: building chai-monorepo app & S3 deploy
          caches:
            - node
          script:
            - apt-get update
            - apt-get install -y zip
            - npm install
            - npm run build
            - zip -r build-chai-monorepo.zip appspec.yml packages/chai-contents-creator-v2/build packages/chai-contents-view-v2/build
            - pipe: atlassian/aws-code-deploy:1.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                ZIP_FILE: "build-chai-monorepo.zip"
                COMMAND: "upload"
                VERSION_LABEL: "build-chai-monorepo-1.0.0"
          artifacts:
            - build-chai-monorepo.zip
      - step:
          name: deploy chai-monorepo app
          script:
            - pipe: atlassian/aws-code-deploy:1.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: "deploy"
                IGNORE_APPLICATION_STOP_FAILURES: "true"
                FILE_EXISTS_BEHAVIOR: "OVERWRITE"
                WAIT: "true"
                VERSION_LABEL: "build-chai-monorepo-1.0.0"
